"""Candidate rule 4's numbers: confusion matrices for the LLM judge.

Ground truth
  same       -- both runs interpreted the SAME source content (no-change
                pairs), or the entity belongs to a root that was not edited
                (control pairs).
  different  -- the entity was generated by the root command that WAS edited
                (definitional pairs).
  no truth   -- downstream pairs: a hand-written lemma whose own statement did
                not change but whose root was edited.  Whether its English
                *should* change is the open question, so these are reported
                against a mechanical indicator instead (see MARKERS).
"""
from __future__ import annotations

import json
import os
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))

# Does the OLD paragraph quote the part of the upstream definition that the
# edit changed?  One marker set per root, taken from the UNCHANGED (A) body:
#   kolvar  m * n + 1        tirneb  3 * x + 1
#   galmuth sums even items  narquil 1 iff n < 5
#   plerx   the even numbers dremnok commutativity
# Imprecise on purpose and reported as such: `narquil_small` / `narquil_large`
# mention five in their OWN statement, so they trip the narquil marker without
# quoting the definition.
MARKERS = {
    "kolvar": ["plus one", "+ 1", "+1", " one"],
    "tirneb": ["three times", "3 * x", "3*x", "three"],
    "galmuth": ["even"],
    "narquil": ["less than five", "less than 5", "n < 5", "five"],
    "plerx": ["even"],
    "dremnok": ["commutat", "commutes", "commute"],
}


def matrix(rows, name):
    same = sum(1 for r in rows if r["same"] is True)
    diff = sum(1 for r in rows if r["same"] is False)
    bad = sum(1 for r in rows if r["same"] is None)
    n = len(rows)
    if not n:
        return
    print(f"  {name:<46} n={n:<5} same={same:<5} different={diff:<5} "
          f"unparsable={bad}   -> 'different' rate {diff/max(n-bad,1):.1%}")


def main() -> None:
    with open(os.path.join(HERE, "judge_phase2.json")) as f:
        jd = json.load(f)
    with open(os.path.join(HERE, "pairs_phase2.json")) as f:
        pd = json.load(f)
    ents = {(e["entity"], e["kind"]): e for e in pd["entities"]}
    sims = {(p["entity"], p["kind"], p["g1"], p["g2"]):
            p["sims"].get("Qwen/Qwen3-Embedding-8B|interp") for p in pd["pairs"]}

    J = jd["judgements"]
    print(f"judge model: {jd['model']}")
    print(f"tokens: {jd['tokens']}")
    print(f"judgements: {len(J)}\n")

    nochange = [r for r in J if r["relation"] == "no-change"]
    control = [r for r in J if r["class"] == "control"]
    defin = [r for r in J if r["class"] == "definitional"]
    downstream = [r for r in J if r["class"] == "downstream"]

    print("=" * 78)
    print("H1. CONFUSION MATRIX")
    print("=" * 78)
    matrix(nochange, "no-change pairs (truth: same)")
    matrix(control, "control pairs, root not edited (truth: same)")
    matrix(defin, "definitional pairs of an edited root (truth: different)")
    matrix(downstream, "downstream pairs (no ground truth)")
    print()

    truth_same = nochange + control
    ok_same = sum(1 for r in truth_same if r["same"] is True)
    ok_diff = sum(1 for r in defin if r["same"] is False)
    n_same = sum(1 for r in truth_same if r["same"] is not None)
    n_diff = sum(1 for r in defin if r["same"] is not None)
    if n_same and n_diff:
        fp = 1 - ok_same / n_same
        fn = 1 - ok_diff / n_diff
        print(f"  no-change called 'changed'      : {n_same-ok_same}/{n_same} "
              f"= {fp:.1%}")
        print(f"  real change called 'unchanged'  : {n_diff-ok_diff}/{n_diff} "
              f"= {fn:.1%}")
        print(f"  savings (propagations suppressed): {1-fp:.1%}")
    print()

    print("=" * 78)
    print("H1b. THE SAME MATRIX WITH A CORRECTED GROUND TRUTH")
    print("     Grade (a) is a COSMETIC edit -- reordered equations, renamed")
    print("     bound variables -- so the entity's meaning genuinely did not")
    print("     change and its English genuinely does not need updating.  A")
    print("     gate that stops propagation there is RIGHT, not wrong.  The")
    print("     matrix above counts those as misses because it labels by 'was")
    print("     the root command edited'; here they count as truth 'same'.")
    print("=" * 78)
    truth_same2 = truth_same + [r for r in defin if r["grade"] == "a-cosmetic"]
    defin2 = [r for r in defin if r["grade"] != "a-cosmetic"]
    ok_same2 = sum(1 for r in truth_same2 if r["same"] is True)
    ok_diff2 = sum(1 for r in defin2 if r["same"] is False)
    n_same2 = sum(1 for r in truth_same2 if r["same"] is not None)
    n_diff2 = sum(1 for r in defin2 if r["same"] is not None)
    fp2 = 1 - ok_same2 / n_same2
    fn2 = 1 - ok_diff2 / n_diff2
    print(f"  no-change (incl. cosmetic) called 'changed': "
          f"{n_same2-ok_same2}/{n_same2} = {fp2:.1%}")
    print(f"  meaning-changing edit called 'unchanged'   : "
          f"{n_diff2-ok_diff2}/{n_diff2} = {fn2:.1%}")
    print(f"  savings (propagations suppressed)          : {1-fp2:.1%}")
    print()

    print("=" * 78)
    print("H1c. STRICTEST GROUND TRUTH: only entities that UNAMBIGUOUSLY")
    print("     changed meaning.  Editing a root command regenerates facts")
    print("     that do not depend on the edited part -- the termination")
    print("     predicate `galmuth_dom` holds for every list whether the")
    print("     function sums the even or the odd entries, and `narquil.cases`")
    print("     splits a `quilm` value the same way whether the threshold is 5")
    print("     or 6.  Counting those as 'must be detected' penalises a")
    print("     comparator for being right.  Here the population is: grade b-f,")
    print("     and either the entity's own printed statement changed, or the")
    print("     entity IS the edited constant/locale (whose printed statement")
    print("     is only its type signature).")
    print("=" * 78)
    expr_same = {(p["entity"], p["kind"], p["g1"], p["g2"]): p["expr_same"]
                 for p in pd["pairs"]}
    must = [r for r in defin
            if r["grade"] != "a-cosmetic"
            and (not expr_same.get((r["entity"], r["kind"], r["g1"], r["g2"]), True)
                 or r["entity"] == r["root"])]
    rest = [r for r in defin if r not in must]
    ok = sum(1 for r in must if r["same"] is False)
    n = sum(1 for r in must if r["same"] is not None)
    truth_same3 = truth_same + rest
    ok3 = sum(1 for r in truth_same3 if r["same"] is True)
    n3 = sum(1 for r in truth_same3 if r["same"] is not None)
    print(f"  unambiguous meaning change called 'unchanged': {n-ok}/{n} = "
          f"{1-ok/n:.1%}")
    print(f"  everything else called 'changed'             : {n3-ok3}/{n3} = "
          f"{1-ok3/n3:.1%}")
    print(f"  savings (propagations suppressed)            : {ok3/n3:.1%}")
    print(f"  (the 'everything else' population folds in the {len(rest)} "
          f"regenerated facts\n   whose meaning does not depend on the edited "
          f"part, plus every cosmetic edit)")
    print("\n  the misses, one line each:")
    for r in must:
        if r["same"] is not False:
            c = sims.get((r["entity"], r["kind"], r["g1"], r["g2"]))
            print(f"    {r['entity']:<22} {r['kind']:<18} {r['grade']:<12} "
                  f"{r['g1']} vs {r['g2']}  cos="
                  f"{'n/a' if c is None else round(c,4)}")
    print("\n  the false alarms, one line each:")
    for r in truth_same3:
        if r["same"] is False:
            c = sims.get((r["entity"], r["kind"], r["g1"], r["g2"]))
            print(f"    {r['entity']:<22} {r['kind']:<18} "
                  f"{str(r['grade']):<12} {r['g1']} vs {r['g2']}  cos="
                  f"{'n/a' if c is None else round(c,4)}")
            print(f"      why: {r['why'][:170]}")
    print()

    print("=" * 78)
    print("H1d. THE RECOMMENDED RULE, swept: propagate if the judge says")
    print("     'different' OR the cosine similarity is below a cut.  Strict")
    print("     ground truth of H1c.  The embedding is a backstop only: the")
    print("     judge's one miss is a pair whose paragraphs are 0.61 similar,")
    print("     which any loose cut catches.")
    print("=" * 78)

    def cos3(r):
        return sims.get((r["entity"], r["kind"], r["g1"], r["g2"]))

    print(f"  {'cut':>8} | {'no-change called changed':>26} | "
          f"{'real change called unchanged':>30} | savings")
    for t in [0.0, 0.50, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90]:
        fp = sum(1 for r in truth_same3
                 if r["same"] is False or (cos3(r) if cos3(r) is not None else 1.0) < t)
        fn = sum(1 for r in must
                 if r["same"] is not False
                 and (cos3(r) if cos3(r) is not None else 1.0) >= t)
        print(f"  {t:>8.2f} | {fp}/{len(truth_same3)} = {fp/len(truth_same3):>13.1%} | "
              f"{fn}/{len(must)} = {fn/len(must):>17.1%} | "
              f"{1-fp/len(truth_same3):>6.1%}")
    print()

    print("=" * 78)
    print("H2. DEFINITIONAL PAIRS BY GRADE (truth: different)")
    print("=" * 78)
    by = defaultdict(list)
    for r in defin:
        by[r["grade"]].append(r)
    for g in sorted(by):
        matrix(by[g], f"grade {g}")
    print()

    print("=" * 78)
    print("H3. NO-CHANGE PAIRS BY WHICH RUNS (truth: same)")
    print("=" * 78)
    by = defaultdict(list)
    for r in nochange:
        by[(r["g1"], r["g2"])].append(r)
    for g in sorted(by):
        matrix(by[g], f"{g[0]} vs {g[1]}")
    print()

    print("=" * 78)
    print("H4. DOWNSTREAM PAIRS: judge verdict vs whether the OLD paragraph")
    print("    quotes the changed part of the upstream definition")
    print("=" * 78)
    tab = defaultdict(lambda: [0, 0])
    detail = []
    for r in downstream:
        e = ents[(r["entity"], r["kind"])]
        old = (e["runs"][r["g1"]]["interpretation"] or "").lower()
        marks = MARKERS.get(r["root"], [])
        quotes = any(m.lower() in old for m in marks)
        if r["same"] is None:
            continue
        tab[(quotes, r["same"])][0] += 1
        detail.append((r, quotes))
    print(f"  {'old paragraph quotes the definition':<38} "
          f"{'judge: same':>12} {'judge: different':>18}")
    for quotes in (True, False):
        s = tab[(quotes, True)][0]
        d = tab[(quotes, False)][0]
        print(f"  {str(quotes):<38} {s:>12} {d:>18}")
    print()
    print("  by grade:")
    by = defaultdict(lambda: [0, 0, 0, 0])   # same/diff x quotes/not
    for r, qz in detail:
        i = (0 if qz else 2) + (0 if r["same"] else 1)
        by[r["grade"]][i] += 1
    print(f"  {'grade':<18} {'quotes+same':>12} {'quotes+diff':>12} "
          f"{'noquote+same':>13} {'noquote+diff':>13}")
    for g in sorted(by):
        a, b, c, d = by[g]
        print(f"  {g:<18} {a:>12} {b:>12} {c:>13} {d:>13}")
    print()

    print("=" * 78)
    print("H6. COMBINED RULE: propagate if the judge says 'different' OR the")
    print("    cosine similarity is below a cut.  The embedding is used only to")
    print("    catch what the judge lets through, so it can only add false")
    print("    alarms; the sweep says how many, for how many misses saved.")
    print("    Evaluated on the judged pairs only, with the corrected ground")
    print("    truth of H1b.")
    print("=" * 78)

    def cos_of(r):
        return sims.get((r["entity"], r["kind"], r["g1"], r["g2"]))

    print(f"  {'cut':>8} | {'no-change called changed':>26} | "
          f"{'real change called unchanged':>30} | savings")
    for t in [0.0, 0.75, 0.80, 0.85, 0.88, 0.90, 0.92, 0.95, 0.97]:
        fp = sum(1 for r in truth_same2
                 if r["same"] is False or (cos_of(r) or 1.0) < t)
        fn = sum(1 for r in defin2
                 if r["same"] is not False and (cos_of(r) or 1.0) >= t)
        print(f"  {t:>8.2f} | {fp}/{len(truth_same2)} = {fp/len(truth_same2):>13.1%} | "
              f"{fn}/{len(defin2)} = {fn/len(defin2):>17.1%} | "
              f"{1-fp/len(truth_same2):>6.1%}")
    print()

    print("=" * 78)
    print("H5. WHERE THE JUDGE AND THE EMBEDDING DISAGREE (10 examples each way)")
    print("=" * 78)
    wrong_same = [r for r in defin if r["same"] is True]
    wrong_diff = [r for r in truth_same if r["same"] is False]
    for title, rows in (("real change the judge called SAME", wrong_same),
                        ("no-change the judge called DIFFERENT", wrong_diff)):
        print(f"\n-- {title}: {len(rows)}")
        for r in rows[:10]:
            s = sims.get((r["entity"], r["kind"], r["g1"], r["g2"]))
            e = ents[(r["entity"], r["kind"])]
            print(f"   {r['entity']} [{r['kind']}] {r['g1']} vs {r['g2']} "
                  f"grade={r['grade']} cos={s if s is None else round(s,4)}")
            print(f"     why: {r['why'][:200]}")
            print(f"     1: {(e['runs'][r['g1']]['interpretation'] or '')[:220]}")
            print(f"     2: {(e['runs'][r['g2']]['interpretation'] or '')[:220]}")


if __name__ == "__main__":
    sys.exit(main())
